/// Interface for objects that can be converted to a JSON-compatible map.
///
/// Implement this on your BLoC states or events so that [BlocPreviewObserver]
/// can serialize them into structured data for the web dashboard.
///
/// ```dart
/// class CounterState implements JsonEncodable {
///   const CounterState({required this.count});
///   final int count;
///
///   @override
///   Map<String, dynamic> toJson() => {'count': count};
/// }
/// ```
///
/// If your state already has a `toJson()` method (e.g. generated by
/// `json_serializable`), you do **not** need to implement this interface —
/// the observer will detect and call it automatically.
abstract interface class JsonEncodable {
  /// Converts this object to a JSON-compatible [Map].
  Map<String, dynamic> toJson();
}
